FROM clux/muslrust:1.62.0 AS builder
COPY Cargo.toml Cargo.lock /volume/
ADD src /volume/src
RUN --mount=type=cache,target=/volume/target \
    --mount=type=cache,target=/root/.cargo/registry \
    --mount=type=cache,target=/root/.cargo/git \
    cargo build --bin piggyback-proxy --release && cp /volume/target/x86_64-unknown-linux-musl/release/piggyback-proxy /volume/piggyback-proxy


FROM scratch
COPY --from=builder /volume/piggyback-proxy /piggyback-proxy
CMD ["/piggyback-proxy"]
