FROM clux/muslrust:1.62.0 AS builder
COPY Cargo.toml Cargo.lock /volume/
ADD piggyback-common /volume/piggyback-common
ADD piggyback-cli /volume/piggyback-cli
ADD piggyback-proxy /volume/piggyback-proxy
RUN --mount=type=cache,target=/volume/target \
    --mount=type=cache,target=/root/.cargo/registry \
    --mount=type=cache,target=/root/.cargo/git \
    cargo build --bin piggyback-proxy --release && cp /volume/target/x86_64-unknown-linux-musl/release/piggyback-proxy /volume/piggyback-proxy-binary


FROM scratch
COPY --from=builder --chmod=777 /volume/piggyback-proxy-binary /piggyback-proxy
CMD ["/piggyback-proxy"]
